name: tests

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

jobs:
  deploy:
    name: Test code
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Deploy Project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependency
        run: yarn install

      - name: Run test
        run: yarn run test
